name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  
jobs:
  deployment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: npm install
      - name: install frontend
        run: npm run install:frontend
      - name: install backend
        run: npm run install:backend
      - name: build
        run: npm run build:frontend
      - name: test backend
        run: npm run test:backend
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: test frontend
        run: npm run test:frontend
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: amazing-message-board
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://amazing-message-board.herokuapp.com/healthcheck"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true